#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#genera los 10 espacios de trabajo
bspc monitor -d I II III IV V VI VII VIII IX X

#1 2 3 4 5 6 7 8 9 10

#I II III IV V VI VII VIII IX X

#inicio de polybar con 1 segundo de espera
sleep 1
$HOME/.config/polybar/launch.sh $

#fondo de pantalla
nitrogen --restore &

#polkit app que requieren sudo
lxqt-policykit-agent &

#picom
picom &

#resolucion
xrandr --output HDMI-A-1 --mode 1920x1080

#añadir resolucion 4:3
#xrandr --newmode "1440x1080_60.00"  129.00  1440 1528 1680 1920  1080 1083 1087 1120 -hsync +vsync
#xrandr --addmode HDMI-A-1 1440x1080_60.00
xrandr --newmode "1440x1080_75.00"  165.25  1440 1544 1696 1952  1080 1083 1087 1130 -hsync +vsync
xrandr --addmode HDMI-A-1 1440x1080_75.00

bspc config border_width         2
bspc config window_gap          12

# Configurar los bordes de las ventanas activas y no activas
bspc config border_width 4
bspc config border_radius 10
bspc config focused_border_color "#63e6f9"
bspc config normal_border_color "#282828"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#abrir apps
bspc rule -a discord desktop='^10'

#move and resize
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

#tema
./.config/bspwm/scrpts/tema.sh
